# Site settings
title: Markus Kauppila
email: markus.kauppila@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: markuskauppila
github_username:  mkauppila

paginate: 10

sass:
    sass_dir: _sass # make sure @import works

# Build settings
markdown: kramdown
